# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalendarWindow(object):
    def setupUi(self, CalendarWindow):
        CalendarWindow.setObjectName("CalendarWindow")
        CalendarWindow.resize(360, 570)
        self.centralwidget = QtWidgets.QWidget(CalendarWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarLayput = QtWidgets.QFrame(self.centralwidget)
        self.calendarLayput.setGeometry(QtCore.QRect(0, 0, 361, 541))
        self.calendarLayput.setMaximumSize(QtCore.QSize(361, 16777215))
        self.calendarLayput.setObjectName("calendarLayput")
        self.clendarLayout_2 = QtWidgets.QVBoxLayout(self.calendarLayput)
        self.clendarLayout_2.setObjectName("clendarLayout_2")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.calendarLayput)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.clendarLayout_2.addWidget(self.calendarWidget_2)
        self.filterButton_2 = QtWidgets.QPushButton(self.calendarLayput)
        self.filterButton_2.setObjectName("filterButton_2")
        self.clendarLayout_2.addWidget(self.filterButton_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.LabelAuthor_2 = QtWidgets.QLabel(self.calendarLayput)
        self.LabelAuthor_2.setObjectName("LabelAuthor_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LabelAuthor_2)
        self.LineEditAuthor_2 = QtWidgets.QLineEdit(self.calendarLayput)
        self.LineEditAuthor_2.setObjectName("LineEditAuthor_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEditAuthor_2)
        self.LabelName_2 = QtWidgets.QLabel(self.calendarLayput)
        self.LabelName_2.setObjectName("LabelName_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LabelName_2)
        self.LineEditName_2 = QtWidgets.QLineEdit(self.calendarLayput)
        self.LineEditName_2.setObjectName("LineEditName_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEditName_2)
        self.LabelGuest_2 = QtWidgets.QLabel(self.calendarLayput)
        self.LabelGuest_2.setObjectName("LabelGuest_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LabelGuest_2)
        self.LineEditGuest_2 = QtWidgets.QLineEdit(self.calendarLayput)
        self.LineEditGuest_2.setObjectName("LineEditGuest_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEditGuest_2)
        self.LabelPlace_2 = QtWidgets.QLabel(self.calendarLayput)
        self.LabelPlace_2.setObjectName("LabelPlace_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.LabelPlace_2)
        self.LineEditPlace_2 = QtWidgets.QLineEdit(self.calendarLayput)
        self.LineEditPlace_2.setObjectName("LineEditPlace_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEditPlace_2)
        self.clendarLayout_2.addLayout(self.formLayout_2)
        CalendarWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CalendarWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName("menubar")
        CalendarWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CalendarWindow)
        self.statusbar.setObjectName("statusbar")
        CalendarWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CalendarWindow)
        QtCore.QMetaObject.connectSlotsByName(CalendarWindow)

    def retranslateUi(self, CalendarWindow):
        _translate = QtCore.QCoreApplication.translate
        CalendarWindow.setWindowTitle(_translate("CalendarWindow", "Календарь"))
        self.filterButton_2.setText(_translate("CalendarWindow", "Фильтруется/Нет"))
        self.LabelAuthor_2.setText(_translate("CalendarWindow", "Автор"))
        self.LabelName_2.setText(_translate("CalendarWindow", "Название"))
        self.LabelGuest_2.setText(_translate("CalendarWindow", "Гость"))
        self.LabelPlace_2.setText(_translate("CalendarWindow", "Место"))
