# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\equipment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_equipmentDialog(object):
    def setupUi(self, equipmentDialog):
        equipmentDialog.setObjectName("equipmentDialog")
        equipmentDialog.resize(400, 110)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(equipmentDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.NameLabel = QtWidgets.QLabel(equipmentDialog)
        self.NameLabel.setObjectName("NameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.NameLabel)
        self.NameLineEdit = QtWidgets.QLineEdit(equipmentDialog)
        self.NameLineEdit.setObjectName("NameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.NameLineEdit)
        self.detailsLabel = QtWidgets.QLabel(equipmentDialog)
        self.detailsLabel.setObjectName("detailsLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.detailsLabel)
        self.detailsLineEdit = QtWidgets.QLineEdit(equipmentDialog)
        self.detailsLineEdit.setObjectName("detailsLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.detailsLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CancelPushButton_3 = QtWidgets.QPushButton(equipmentDialog)
        self.CancelPushButton_3.setObjectName("CancelPushButton_3")
        self.horizontalLayout.addWidget(self.CancelPushButton_3)
        self.SavePushButton = QtWidgets.QPushButton(equipmentDialog)
        self.SavePushButton.setObjectName("SavePushButton")
        self.horizontalLayout.addWidget(self.SavePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(equipmentDialog)
        QtCore.QMetaObject.connectSlotsByName(equipmentDialog)

    def retranslateUi(self, equipmentDialog):
        _translate = QtCore.QCoreApplication.translate
        equipmentDialog.setWindowTitle(_translate("equipmentDialog", "Оборудование"))
        self.NameLabel.setText(_translate("equipmentDialog", "Название"))
        self.detailsLabel.setText(_translate("equipmentDialog", "Детали"))
        self.CancelPushButton_3.setText(_translate("equipmentDialog", "Отмена"))
        self.SavePushButton.setText(_translate("equipmentDialog", "Сохранить"))
