# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'link.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_linkDialog(object):
    def setupUi(self, linkDialog):
        linkDialog.setObjectName("linkDialog")
        linkDialog.resize(400, 165)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(linkDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.fioLabel = QtWidgets.QLabel(linkDialog)
        self.fioLabel.setObjectName("fioLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fioLabel)
        self.fioLineEdit = QtWidgets.QLineEdit(linkDialog)
        self.fioLineEdit.setObjectName("fioLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fioLineEdit)
        self.jobTitleLabel = QtWidgets.QLabel(linkDialog)
        self.jobTitleLabel.setObjectName("jobTitleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.jobTitleLabel)
        self.jobTitleLineEdit = QtWidgets.QLineEdit(linkDialog)
        self.jobTitleLineEdit.setObjectName("jobTitleLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.jobTitleLineEdit)
        self.connectionLabel = QtWidgets.QLabel(linkDialog)
        self.connectionLabel.setObjectName("connectionLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.connectionLabel)
        self.connectionLineEdit = QtWidgets.QLineEdit(linkDialog)
        self.connectionLineEdit.setObjectName("connectionLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.connectionLineEdit)
        self.additionLabel = QtWidgets.QLabel(linkDialog)
        self.additionLabel.setObjectName("additionLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.additionLabel)
        self.additionLineEdit = QtWidgets.QLineEdit(linkDialog)
        self.additionLineEdit.setObjectName("additionLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.additionLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CancelPushButton_3 = QtWidgets.QPushButton(linkDialog)
        self.CancelPushButton_3.setObjectName("CancelPushButton_3")
        self.horizontalLayout.addWidget(self.CancelPushButton_3)
        self.SavePushButton = QtWidgets.QPushButton(linkDialog)
        self.SavePushButton.setObjectName("SavePushButton")
        self.horizontalLayout.addWidget(self.SavePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(linkDialog)
        QtCore.QMetaObject.connectSlotsByName(linkDialog)

    def retranslateUi(self, linkDialog):
        _translate = QtCore.QCoreApplication.translate
        linkDialog.setWindowTitle(_translate("linkDialog", "Связной"))
        self.fioLabel.setText(_translate("linkDialog", "ФИО"))
        self.jobTitleLabel.setText(_translate("linkDialog", "Должность"))
        self.connectionLabel.setText(_translate("linkDialog", "Связь"))
        self.additionLabel.setText(_translate("linkDialog", "Дополнение"))
        self.CancelPushButton_3.setText(_translate("linkDialog", "Отмена"))
        self.SavePushButton.setText(_translate("linkDialog", "Сохранить"))
