# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectDialog(object):
    def setupUi(self, SelectDialog):
        SelectDialog.setObjectName("SelectDialog")
        SelectDialog.resize(190, 275)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SelectDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.eventButton = QtWidgets.QPushButton(SelectDialog)
        self.eventButton.setObjectName("eventButton")
        self.verticalLayout.addWidget(self.eventButton)
        self.placeButton = QtWidgets.QPushButton(SelectDialog)
        self.placeButton.setObjectName("placeButton")
        self.verticalLayout.addWidget(self.placeButton)
        self.linkButton = QtWidgets.QPushButton(SelectDialog)
        self.linkButton.setObjectName("linkButton")
        self.verticalLayout.addWidget(self.linkButton)
        self.equipmentButton = QtWidgets.QPushButton(SelectDialog)
        self.equipmentButton.setObjectName("equipmentButton")
        self.verticalLayout.addWidget(self.equipmentButton)
        self.authorButton = QtWidgets.QPushButton(SelectDialog)
        self.authorButton.setObjectName("authorButton")
        self.verticalLayout.addWidget(self.authorButton)
        self.userButton = QtWidgets.QPushButton(SelectDialog)
        self.userButton.setObjectName("userButton")
        self.verticalLayout.addWidget(self.userButton)
        self.workerButton = QtWidgets.QPushButton(SelectDialog)
        self.workerButton.setObjectName("workerButton")
        self.verticalLayout.addWidget(self.workerButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SelectDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectDialog)

    def retranslateUi(self, SelectDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectDialog.setWindowTitle(_translate("SelectDialog", "Добавить"))
        self.eventButton.setText(_translate("SelectDialog", "Мероприятие"))
        self.placeButton.setText(_translate("SelectDialog", "Место"))
        self.linkButton.setText(_translate("SelectDialog", "Связной"))
        self.equipmentButton.setText(_translate("SelectDialog", "Оборудование"))
        self.authorButton.setText(_translate("SelectDialog", "Автор"))
        self.userButton.setText(_translate("SelectDialog", "Пользователь"))
        self.workerButton.setText(_translate("SelectDialog", "Работник"))
